---
- name: Reload Systemd Daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Restart kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Reload the sysctl
  ansible.builtin.command: sysctl --system
  ignore_errors: true
