---
- name: Create hosts list from inventory
  ansible.builtin.set_fact:
    etc_hosts_inventory_block: |-
      {% for item in (groups['k8s_cluster']) | unique -%}
      {% if 'access_ip' in hostvars[item] or 'ip' in hostvars[item] or 'ansible_default_ipv4' in hostvars[item] or 'ansible_host' in hostvars[item] -%}
      {{ hostvars[item]['access_ip'] | default(hostvars[item]['ip'] | default(hostvars[item]['ansible_default_ipv4']['address']) | default(hostvars[item]['ansible_host'])) }}
      {%- if ('ansible_hostname' in hostvars[item] and item != hostvars[item]['ansible_hostname']) %} {{ hostvars[item]['ansible_hostname'] }}.{{ etc_hosts_dns_domain }} {{ hostvars[item]['ansible_hostname'] }} {% else %} {{ item }}.{{ etc_hosts_dns_domain }} {{ item }} {% endif %}

      {% endif %}
      {% endfor %}
  delegate_to: localhost
  connection: local
  delegate_facts: true
  run_once: true

- name: Populate inventory into hosts file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: "{{ hostvars.localhost.etc_hosts_inventory_block }}"
    create: yes
    backup: yes
    unsafe_writes: yes
    marker: "# Ansible inventory hosts {mark}"
    mode: 0644
