---
- name: Check if Helm binary exists.
  stat:
    path: "{{ bin_dir }}/helm"
  register: helm_check

- name: Check Helm version.
  command: >
    {{ bin_dir }}/helm version --client --template
    {{ "'{{ if .Version }}{{ .Version }}{{ else }}{{ .Client.SemVer }}{{ end }}'" }}
  failed_when: no
  changed_when: no
  register: helm_current_version
  when: helm_check.stat.exists

- name: Helm current version
  debug:
    msg: '{{ helm_current_version.stdout }}'
  when: 
    - helm_check.stat.exists
    - helm_current_version.rc == 0

- name: Install helm.
  block:
    - name: Download helm.
      unarchive:
        src: https://get.helm.sh/helm-{{ helm_version }}-{{ k8s_platform }}-{{ k8s_arch }}.tar.gz
        dest: /tmp
        remote_src: true

    - name: Copy helm binary.
      copy:
        src: "/tmp/{{ k8s_platform }}-{{ k8s_arch }}/helm"
        dest: "{{ bin_dir }}"
        mode: 0755
        remote_src: true

  when: >
    not helm_check.stat.exists
    or helm_current_version.stdout != helm_version
