services:
  repo-nginx:
    image: nginx:1.23.3-alpine-slim
    hostname: repo-nginx
    container_name: repo-nginx
    restart: unless-stopped
    volumes:
      - /srv/cd-debian-12.7.0:/srv/repo-cd:ro
      - /srv/apt-cacher-os/cache:/srv/repo-os:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates/:/etc/nginx/templates/:ro
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - my-network
    ports:
      - '80:80'

networks:
  my-network:
    external: true
    name: my-network
