services:
  dns:
    image: localdns:0.1
    build: ./dnsmasq
    container_name: localdns
    restart: unless-stopped
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf:ro
      # - /srv/localdns/:/var/log/dnsmasq/:rw

    network_mode: "host"
    cap_add:
      - NET_BIND_SERVICE
