services:
  proxy:
    image: nginx:1.23.3-alpine-slim
    hostname: proxy
    container_name: proxy
    depends_on:
      - flask
    volumes:
      - ./auth:/etc/nginx/auth
      - ./content:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates/:/etc/nginx/templates/:ro
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      TZ: 'Europe/Moscow'
      FLASK_URL: 'flask-app:5000'
    networks:
      - my-network
    ports:
      - '80:80'
      - '443:443'
    # restart: unless-stopped

  flask:
    build: ./flask
    image: flask:0.0.1
    container_name: flask
    volumes:
      - ./flask/code:/code:ro
    environment:
      - FLASK_APP=/code/main.py
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
          - flask-app
    # ports:
    #   - '8080:5000'

networks:
  my-network:
    name: my-network
